"""add status enum

Revision ID: 4ab701cd454e
Revises: 94797d295ffe
Create Date: 2025-11-07 15:09:35.561626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab701cd454e'
down_revision: Union[str, Sequence[str], None] = '94797d295ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('new', 'in_progress', 'resolved', 'closed', name='status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('new', 'in_progress', 'resolved', 'closed', name='status_enum'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
